# Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# https://aws.amazon.com/agreement
# SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: 2010-09-09
Description: Deploys the Secrets Manager Backup application via a Service Catalog product.

#:=====
#
# Metadata
#
#:=====

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Resource Location Configuration
        Parameters:
          - pResourceLocationBucket
          - pResourceLocationBucketRegion
          - pResourceLocationBucketKeyPrefix
      -
        Label:
          default: Service Catalog Configuration
        Parameters:
          - pServiceCatalogPortfolioId
          - pServiceCatalogProductOwner
          - pServiceCatalogPortfolioProvider
          - pServiceCatalogPortfolioAssociationPrincipalARN
    ParameterLabels:
      pResourceLocationBucket:
        default: Bucket Name
      pResourceLocationBucketKeyPrefix:
        default: Object Prefix
      pResourceLocationBucketRegion:
        default: Bucket Region
      pServiceCatalogPortfolioAssociationPrincipalARN:
        default: Principal ARN
      pServiceCatalogPortfolioId:
        default: Portfolio ID
      pServiceCatalogPortfolioProvider:
        default: Portfolio Provider
      pServiceCatalogProductOwner:
        default: Product Owner

#:=====
#
# Parameters
#
#:=====

Parameters:
  pResourceLocationBucket:
    Type: String
    AllowedPattern: ^(?!\.)(?:\.?(?!-)[a-z\d\-]+(?<!-))$
    ConstraintDescription: >-
      Parameter must contain only lower-case letters, numbers, periods, or hyphens, and may not start or end with a
      period or hyphen or have periods next to hyphens, and be between 3 and 63 characters in length.
    Description: The name of the S3 bucket that contains the deployment resource files.
    MaxLength: 63
    MinLength: 3

  pResourceLocationBucketKeyPrefix:
    Type: String
    AllowedPattern: ^[^\s]*$
    ConstraintDescription: Parameter must not contain any whitespace.
    Default: ""
    Description: >-
      The S3 object key prefix accounting for any folder structure within the bucket that contains the deployment
      resource files.  Do not include any leading or trailing slashes.
    MaxLength: 1024

  pResourceLocationBucketRegion:
    Type: String
    AllowedPattern: ^(?:(?:us(?:-gov)?|af|ap|ca|cn|eu|me|sa)-(?:central|(?:north|south)?(?:east|west)?)-\d)?$
    ConstraintDescription: Parameter must be a valid AWS Region.
    Default: ""
    Description: >-
      The region of the S3 bucket that contains the deployment resource files.  Leave blank to use the current region of
      the stack.

  pServiceCatalogPortfolioAssociationPrincipalARN:
    Type: String
    AllowedPattern: ^(?:arn:aws(?:-cn|-us-gov)?:iam::\d{12}:(?:group|role|user)\/[\w\-+=,.@]+)?$
    ConstraintDescription: Parameter must be a valid IAM group, role, or user ARN.
    Default: ""
    Description: >-
      An IAM group, role, or user to allow access to the automatically generated Secrets Manager Backup Service Catalog
      portfolio.  Required if no existing portfolio ID is provided.

  pServiceCatalogPortfolioId:
    Type: String
    AllowedPattern: ^(?:port-[a-z\d]{13})?$
    ConstraintDescription: Parameter must be a valid Service Catalog portfolio ID.
    Default: ""
    Description: >-
      A Service Catalog portfolio ID with which to associate the Secrets Manager Backup application product.  A new
      portfolio will be made if left empty.

  pServiceCatalogPortfolioProvider:
    Type: String
    Default: Portfolio Provider
    Description: >-
      A name identified as the provider of the automatically generated Secrets Manager Backup Service Catalog portfolio.
      Required if no existing portfolio ID is provided.

  pServiceCatalogProductOwner:
    Type: String
    Default: Product Owner
    Description: A name identified as the owner of the Secrets Manager Backup Service Catalog product.
    MaxLength: 4096
    MinLength: 1

#:=====
#
# Conditions
#
#:=====

Conditions:
  cCreatePortfolio: !Equals [ !Ref pServiceCatalogPortfolioId, "" ]
  cUseCurrentRegion: !Equals [ !Ref pResourceLocationBucketRegion, "" ]
  cUseS3KeyPrefix: !Not [ !Equals [ !Ref pResourceLocationBucketKeyPrefix, "" ] ]

#:=====
#
# Resources
#
#:=====

Resources:
  rSecretsManagerBackupServiceCatalogPortfolio:
    Type: AWS::ServiceCatalog::Portfolio
    Condition: cCreatePortfolio
    Properties:
      Description: Secrets Manager Backup application portfolio.
      DisplayName: Secrets Manager Backup Portfolio
      ProviderName: !Ref pServiceCatalogPortfolioProvider

  rSecretsManagerBackupServiceCatalogPortfolioPrincipalAssociation:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Condition: cCreatePortfolio
    Properties:
      PortfolioId: !Ref rSecretsManagerBackupServiceCatalogPortfolio
      PrincipalARN: !Ref pServiceCatalogPortfolioAssociationPrincipalARN
      PrincipalType: IAM

  rSecretsManagerBackupServiceCatalogPortfolioProductAssociation:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId: !If [ cCreatePortfolio, !Ref rSecretsManagerBackupServiceCatalogPortfolio, !Ref pServiceCatalogPortfolioId ]
      ProductId: !Ref rSecretsManagerBackupServiceCatalogCloudFormationProduct

  rSecretsManagerBackupServiceCatalogCloudFormationProduct:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Description: >-
        Deploy an application that will backup Secrets Manager secrets from regions in specified accounts to a region in
        an identified backup account.
      Name: Secrets Manager Backup
      Owner: !Ref pServiceCatalogProductOwner
      ProvisioningArtifactParameters:
        -
          Info:
            LoadTemplateFromURL: !Sub
              - https://${ pResourceLocationBucket }.s3.${ Region }.amazonaws.com/${ Prefix }secrets_manager_backup.baseline.product.template.yml
              -
                Region: !If [ cUseCurrentRegion, !Ref AWS::Region, !Ref pResourceLocationBucketRegion ]
                Prefix: !If [ cUseS3KeyPrefix, !Sub "${ pResourceLocationBucketKeyPrefix }/" , "" ]
          Name: v1.0.0

#:=====
#
# Outputs
#
#:=====

Outputs: {}
