# Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# https://aws.amazon.com/agreement
# SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template deploys the IAM resources to facilitate cross-account backups of Secrets Manager secrets completed by
  the Secrets Manager Backup application.

#:=====
#
# Metadata
#
#:=====

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Backup Configuration
        Parameters:
          - pBackupAccountId
          - pBackupRegion
    ParameterLabels:
      pBackupAccountId:
        default: Account ID
      pBackupRegion:
        default: Region

#:=====
#
# Parameters
#
#:=====

Parameters:
  pBackupAccountId:
    Type: String
    AllowedPattern: ^\d{12}$
    ConstraintDescription: Parameter must be a valid AWS account ID.
    Description: The account ID identified as the backup location for the Secrets Manager Backup application.

  pBackupRegion:
    Type: String
    AllowedPattern: ^(?:us(?:-gov)?|af|ap|ca|cn|eu|me|sa)-(?:central|(?:north|south)?(?:east|west)?)-\d$
    ConstraintDescription: Parameter must be a valid AWS Region.
    Description: The region identified as the backup location for the Secrets Manager Backup application.

#:=====
#
# Resources
#
#:=====

Resources:
  rSecretsManagerBackupIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          -
            Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${ pBackupAccountId }:role/secrets_manager_backup/backup_execution_role
        Version: 2012-10-17
      Path: /secrets_manager_backup/
      Policies:
        -
          PolicyDocument:
            Statement:
              -
                Action: kms:Decrypt
                Condition:
                  StringLike:
                    kms:ViaService:
                      - secretsmanager.*.amazonaws.com
                Effect: Allow
                Resource: !Sub arn:aws:kms:*:${ AWS::AccountId }:key/*
              -
                Action:
                  - secretsmanager:DescribeSecret
                  - secretsmanager:GetSecretValue
                Effect: Allow
                Resource: !Sub arn:aws:secretsmanager:*:${ AWS::AccountId }:secret:*
            Version: 2012-10-17
          PolicyName: backup_assume_role_policy
      RoleName: backup_assume_role

  rSecretsManagerBackupEventBusIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          -
            Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
        Version: 2012-10-17
      Path: /secrets_manager_backup/
      Policies:
        -
          PolicyDocument:
            Statement:
              -
                Action: events:PutEvents
                Effect: Allow
                Resource: !Sub arn:aws:events:${ pBackupRegion }:${ pBackupAccountId }:event-bus/SecretsManagerBackupEventBus
            Version: 2012-10-17
          PolicyName: backup_event_bus_role_policy
      RoleName: backup_event_bus_role

#:=====
#
# Outputs
#
#:=====

Outputs: {}
